<?php

namespace app\shop\controller\pay;

use app\shop\controller\Base;
use think\Controller;
use think\Db;

/**
 * 余额支付 支付类
 */
class Balancepay extends Base {



    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub


    }



}
