<?php

namespace app\shop\controller\pay;

use think\Controller;
use think\Db;
use app\common\controller\Hm;
use think\Config;

/**
 * 捷支付支付类
 */
class Jpay extends Controller {

    public $gateway_url = "http://pay.joo.life/Corder";
    public $domain = "";

    protected $site = []; //系统配置信息

    public $jpay = []; //配置信息

    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(isset($_SERVER['REQUEST_SCHEME'])){
            $this->domain = $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['HTTP_HOST'] . '/';
        }else{
            $this->domain = 'http://' . $_SERVER['HTTP_HOST'] . '/';
        }
        $this->site = Config::get("site");

        $jpay_result = db::name('pay')->where(['type' => 'jpay'])->find();
        $this->jpay = json_decode($jpay_result['value'], true);
    }



    /**
     * 发起支付
     * @params $order 订单信息
     * @params $goods 商品信息
     * @params $pay_type 支付类型 alipay  wxpay
     * @table 订单表 一般有商品订单表和余额充值订单表
     * M时参数必选，为O时可选，为C时需要依赖于其它字段
     */
    public function pay($order, $goods, $pay_type){

//  echo $pay_type;die;

        $data = [
            'appid' => $this->jpay['appid'], // 应用id
            'is_ok' => "true",
            'diy' => 1,
            'sign' => md5($this->jpay['appid'] . $this->jpay['apptoken']),
            'code' => $pay_type == 'jpay_alipay' ? 1 : 2,
            'order_id' => $order['order_no'], //商户订单号
            'order_rmb' => $order['money'],
        ];

        
        header("location: " . $this->gateway_url . "?" . http_build_query($data));
        die;

        // echo "<pre>"; print_r($data);

        $result = hmCurl($this->gateway_url, http_build_query($data));
        
        // var_dump($result);die;
        $result = json_decode($result, true);
        
        echo '<pre>'; print_r($result);die;
        
        if($result['state'] != "succeeded"){
            $this->error($result['message']);
        }
        //写入支付二维码
        db::name('order')->where(['id' => $order['id']])->update(['qr_code' => $result['return_data']['url']]);
        header("location: /aliprecreate.html?out_trade_no=" . $order['order_no']);
        die;
        

    }


    /**
     * 生成签名
     */
    public function getSign($data){
        ksort($data);
        $data_str = "";
        foreach($data as $key => $val) {
            if ($key != "sign"){
                $data_str .= $key . "=" . $val . "&";
            }
        }
        $data_str = rtrim($data_str, "&");
        $data_str = $data_str . $this->yfpay['app_key'];
        $sign = md5($data_str);
        $sign = strtolower($sign);
        return $sign;
    }

}
