<?php

return array (
  'shop_title' => '红盟云卡 - 基于PHP + MySQL打造的商城建站系统',
  'shop_pet_name' => '红盟云卡',
  'beian' => '',
  'version' => '1654850585',
  'min_cashout' => '0',
  'max_cashout_num' => '3',
  'cashout_charged' => '1',
  'tourist_buy' => '1',
  'login' => '1',
  'register' => '1',
  'statistics' => '',
  'diy_name' => '商品购买',
  'buy_account' => '0',
  'buy_password' => '0',
  'tip_account' => '',
  'tip_password' => '游客查询订单时的凭证',
  'eject_goods' => '',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_verify_type' => '2',
  'mail_smtp_port' => '465',
  'mail_smtp_pass' => '',
  'mail_smtp_user' => '红盟云卡',
  'mail_from' => '',
  'admin_order_email' => '0',
  'user_order_email' => '0',
  'ico' => '/assets/img/favicon.png',
  'cdk_order' => 'asc',
);
