<?php

return array (
  'shop_title' => '我的网站',
  'shop_pet_name' => '我的网站',
  'beian' => '',
  'version' => '1658726345',
  'min_cashout' => '0',
  'max_cashout_num' => '3',
  'cashout_charged' => '1',
  'tourist_buy' => '1',
  'login' => '0',
  'register' => '0',
  'statistics' => '',
  'eject_goods' => '<p><br></p>',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_verify_type' => '2',
  'mail_smtp_port' => '465',
  'mail_smtp_pass' => '',
  'mail_smtp_user' => '我的网站',
  'mail_from' => '',
  'admin_order_email' => '0',
  'user_order_email' => '0',
  'ico' => '/assets/img/favicon.png',
);
