<?php

namespace app\index\controller;

use think\Controller;
use think\Db;

/**
 *
 */
class Base extends Controller {

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $active_plugins = Db::name('options')->where(['option_name' => 'active_plugin'])->value('option_content');
        $active_plugins = empty($active_plugins) ? [] : unserialize($active_plugins);
        if ($active_plugins && is_array($active_plugins)) {
            foreach($active_plugins as $plugin) {
                if(true === checkPlugin($plugin)) {
                    include_once(ROOT_PATH . 'public/content/plugin/' . $plugin);
                }
            }
        }

    }



}
