<?php

namespace app\index\controller;


use think\Db;

/**
 *
 */
class Demo extends Base {

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    public function index(){

        $timestamp = time();
        $insert = [];
        for($i = 0; $i < 100000; $i++){
            $insert[] = [
                'goods_id' => 15,
                'type' => 0,
                'cdk' => $i,
                'num' => 1,
                'createtime' => $timestamp
            ];
        }
        Db::name('cdkey')->insertAll($insert);
        $s = time() - $timestamp;
        echo '本次耗时' . $s . '秒';

    }

}
