<?php

namespace app\index\controller;


/**
 *
 */
class JiuwuBalance extends Base {

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    /**
     * 添加监控挂载点
     */
    public function monitor(){
        $password = $this->request->param('password');
        doAction('jiuwu_balance_monitor', $password);
    }

}
