<?php

namespace app\shop\controller;
use app\common\controller\Mask;
use fast\Random;
use think\Config;
use think\Controller;
use think\Db;
use think\Session;
use think\Cache;
use think\Request;
use think\Response;
use think\exception\HttpResponseException;

class Base extends Controller {

    /**
     * 默认响应输出类型,支持json/xml
     * @var string
     */
    protected $responseType = 'json';

    protected $timestamp = 0;


    protected $user = null; //用户信息

    protected $station_id = 0;  //子站id

    protected $site = []; //系统配置信息

    protected $domain = ""; //域名

    protected $equipment = "pc"; //客户端设备

    protected $template_path = ""; //模板路径

    protected $avatar = "/uploads/20210106/634991592083b770187ab213c25d022a.jpg"; //默认头像·

    protected $template_name = "default"; //模板名称

    protected $options = [];


    public function _initialize() {

        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->timestamp = time();
        $this->equipment = is_mobile() ? 'mobile' : 'pc';
        $options = db::name('options')->select();
        foreach($options as $val){
            $this->options[$val['option_name']] = $val['option_content'];
        }
        if(!empty($this->options['active_template'])){
            $active_template = unserialize($this->options['active_template']);
            $this->template_name = $active_template[$this->equipment];
        }
        $template_info_path = ROOT_PATH . 'public/content/template/' . $this->template_name . '/info.php';
        if(!file_exists($template_info_path)){
            die("<br>您未启用任何模板，请前往后台【网站扩展-模板管理】中开启相应模板。<br><br>如您未安装过网站模板，你需要在后台【网站扩展-插件管理-插件市场】选择安装您的模板");
        }
        $this->template_path = ROOT_PATH . 'public/content/template/' . $this->template_name . '/';
        $active_plugins = Db::name('options')->where(['option_name' => 'active_plugin'])->value('option_content');
        $active_plugins = empty($active_plugins) ? [] : unserialize($active_plugins);
        if ($active_plugins && is_array($active_plugins)) {
            foreach($active_plugins as $plugin) {
                if(true === checkPlugin($plugin) && substr($plugin, -13) != '_template.php' && substr($plugin, -8) != '_pay.php') {
                    include_once(ROOT_PATH . 'public/content/plugin/' . $plugin);
                }
            }
        }
        doAction('init');
    }


}
