<?php

namespace app\shop\controller;

use fast\Random;
use think\Db;
use think\Session;

class Complain extends Base {

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    /**
     * 投诉列表
     */
    public function complainList(){
        $list = [];
        $search = false;
        if($this->request->has('name') || $this->request->has('qq')){
            $search = true;
            $where = [
                'name' => $this->request->param('name'),
                'qq' => $this->request->param('qq')
            ];
            $list = db::name('complain')->where($where)->order('id desc')->select();

            foreach($list as &$val){
                if($val['status'] == 0){
                    $val['status'] = '待处理';
                }
                if($val['status'] == 1){
                    $val['status'] = '处理中';
                }
                if($val['status'] == 2){
                    $val['status'] = '处理完成';
                }
            }

        }

        $this->assign([
            'list' => $list,
            'search' => $search
        ]);
        return view('list');
    }

    /**
     * 投诉页面
     */

    public function index() {

        if($this->request->isPost()){
            $post = $this->request->param();
            if(empty($post['name'])) return json(['code' => 400, 'msg' => '称呼不能为空']);
            if(empty($post['qq'])) return json(['code' => 400, 'msg' => '请输入您的联系QQ']);
            if(strlen($post['qq']) > 11) return json(['code' => 400, 'msg' => '请输入正确的QQ号码']);
            if(empty($post['out_trade_no'])) return json(['code' => 400, 'msg' => '请输入您要投诉的订单号']);
            if(empty($post['details'])) return json(['code' => 400, 'msg' => '请输入投诉内容']);
            $insert = [
                'complain_id' => md5(time() . mt_rand(10000, 99999)),
                'name' => $post['name'],
                'qq' => $post['qq'],
                'out_trade_no' => $post['out_trade_no'],
                'details' => $post['details'],
                'create_time' => time(),
            ];
            db::name('complain')->insert($insert);
            return json(['code' => 200, 'msg' => '投诉已提交', 'data' => $insert['complain_id']]);
        }

        $complain = [];
        if($this->request->has('complain_id')){
            $complain_id = $this->request->param('complain_id');
            $complain = db::name('complain')->where(['complain_id' => $complain_id])->find();
//            echo '<pre>'; print_r($complain);die;
            if($complain['status'] == 0){
                $complain['handle_result'] = '待处理';
            }
            if($complain['status'] == 1){
                $complain['handle_result'] = '处理中，请耐心等待结果';
            }
        }

        $this->assign([
            'complain' => $complain,
        ]);
        
        return view();
    }

}
