<?php

namespace app\shop\controller;
use app\common\controller\Hm;
use think\Db;
class Goods extends Base {

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign([
            'navi' => ''
        ]);
    }

    //
    public function detail(){
        if(!$this->request->has('id')){
            $this->error('参数错误');
        }
        $goods_id = $this->request->param('id');

        $user = Hm::getUser();
        // echo '<pre>'; print_r($user);die;

        $goods = Hm::getGoodsInfo($goods_id, $user, $this->options);
        if(!$goods || !empty($goods['deletetime'])){
            return $this->errorPage("该商品已被删除", '如需帮助请联系网站客服人员', '商品不存在', 404);
        }

        if($goods['shelf'] == 1){
            return $this->errorPage("该商品已下架", '如需帮助请联系网站客服人员', '商品不存在', 404);
        }

//         echo '<pre>'; print_r($goods);die;
        $order = db::name('order')->where(['uid' => $user['id']])->order('id desc')->find();

        $goods['eject'] = empty(strip_tags($goods['eject'])) ? null : $goods['eject'];
        $this->assign([
            'title' => $goods['name'],
            'goods' => $goods,
            'order' => $order,
        ]);

//        echo '<pre>'; print_r($goods);die;

        return view($this->template_path . "goods.html");

    }


    //分类下商品列表
    public function lists() {

        if($this->request->isAjax()){
            $post = $this->request->param();
            $order = 'id desc';
            $where = [
                'deletetime' => null,
                'category_id' => empty($post['category']) ? 0 : $post['category']
            ];
            $list = db::name('goods')->where($where)->order($order)->limit($post['offset'], $post['limit'])->select();

            $goods_azf_all = Fun::getGoodsAzfAll();
            $azf_ids = array_column($goods_azf_all, 'id');

            $goods_list = [];
            foreach($list as &$val){
                if($val['type'] == 'own'){
                    $images = explode(',', $val['images']);
                    $val['cover'] = $images[0];
                    $goods_list[] = $val;
                }else if($val['type'] == 'azf'){
                    $key = array_search($val['remote_id'], $azf_ids);
                    if($key){
                        $azf_goods_info = $goods_azf_all[$key];
                        $val['name'] = $azf_goods_info['goodsname'];
                        $val['cover'] = $azf_goods_info['imgurl'];
                        $val['sales'] = $azf_goods_info['salesvolume'];
                        $goods_list[] = $val;
                    }

                }
            }
            $this->success('ok', $goods_list);
        }


        $category_nickname = $this->request->has('category') ? $this->request->param('category') : null;

        $category_info = [];
        if($category_nickname){
            $where = [
                'type' => 'goods',
                'nickname' => $category_nickname
            ];
            $category_info = db::name('category')->where($where)->find();
        }


        $this->assign([
            'category_nickname' => $category_nickname,
            'category_info' => $category_info,
            'footer_active' => 'category',
        ]);

        return view($this->template_path . "list.html");
    }

}
