<?php

namespace app\shop\controller;

use fast\Random;
use think\Db;
use think\Session;

class Register extends Base {

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(session::has('user')){
            header('location: ' . url('user/index'));
            die;
        }
    }

    public function index() {
        if($this->site['register'] == 0){
            $this->error('网站注册功能已关闭！');
        }
        if($this->request->isAjax()){
            $post = $this->request->param();
            Db::startTrans();
            try {
                $account_type = getAccountType($post['account']);
                if($account_type != "email" && $account_type != "mobile"){
                    throw new \Exception("请输入正确的手机号或邮箱");
                }
                $where = [
                    "{$account_type}" => $post['account'],
                ];
                $user = db::name('user')->where($where)->find();
                if($user){
                    $account_text = $account_type == "email" ? '邮箱' : '手机号';
                    throw new \Exception("{$account_text}被占用，请更换其他手机号");
                }
                $insert = [
                    "{$account_type}" => $post['account'],
                    "salt" => Random::alnum(),
                    "nickname" => $post['account'],
                    "createtime" => time(),
                ];
                $insert["password"] = $this->getEncryptPassword($post['password'], $insert['salt']);
                $uid = db::name("user")->insertGetId($insert);
                db::name("options")->where(["option_name" => "user_total"])->setInc("option_content");
                Db::commit();
            }catch (\Exception $e){
                Db::rollback();
                $this->error($e->getMessage());
            }
            if($uid){
                $user = db::name('user')->where(['id' => $uid])->find();
                session::set("user", $user);
                $this->success("注册成功");
            }else{
                $this->error("注册失败");
            }
        }
        
        return view(ROOT_PATH . 'public/content/template/common/register.html');
        return view($this->template_path . "register.html");
    }

}
